from selenium.webdriver.common.by import By
from pages import *


class HeaderLocators:
    username = (By.ID, "UserName")
    password = (By.ID, "Password")
    submit = (By.XPATH, "//input[@value='Войти']")
    logout = (By.XPATH, "//input[@type='submit']")
    dashboard = (By.XPATH, "//li[@title='На главную']")


class SearchVacancyLocators:
    type_source_vacancy = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    name_source_vacancy = (By.XPATH, "(//input[@type='text'])[2]")
    name_vacant_position = (By.XPATH, "(//input[@type='text'])[3]")
    type_vacancy = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")
    profile_activity_organization = (By.XPATH, "(//div[contains(@id, 's2id')])[3]")
    field_professional_activity = (By.XPATH, "(//div[contains(@id, 's2id')])[4]")
    key_word = (By.XPATH, "(//input[@type='text'])[7]")
    category_job = (By.XPATH, "(//div[contains(@id, 's2id')])[5]")
    group_job = (By.XPATH, "(//div[contains(@id, 's2id')])[6]")
    subject_workplace = (By.XPATH, "(//div[contains(@id, 's2id')])[7]")
    region_workplace = (By.XPATH, "(//div[contains(@id, 's2id')])[8]")
    salary_from = (By.XPATH, "(//input[@type='text'])[12]")
    salary_to = (By.XPATH, "(//input[@type='text'])[13]")
    business_trip = (By.XPATH, "(//div[contains(@id, 's2id')])[9]")
    work_day = (By.XPATH, "(//div[contains(@id, 's2id')])[10]")
    day_start_accept_document_from = (By.XPATH, "(//input[@type='text'])[16]")
    day_start_accept_document_to = (By.XPATH, "(//input[@type='text'])[17]")
    day_stop_accept_document_from = (By.XPATH, "(//input[@type='text'])[18]")
    day_stop_accept_document_to = (By.XPATH, "(//input[@type='text'])[19]")
    level_education = (By.XPATH, "(//div[contains(@id, 's2id')])[11]")
    service_experience = (By.XPATH, "(//div[contains(@id, 's2id')])[12]")
    work_experience_speciality = (By.XPATH, "(//div[contains(@id, 's2id')])[13]")


class ControlVacancyLocators:
    status_response = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")


class DocumentsLocators:
    name_document = (By.XPATH, "//div[contains(@id, 's2id')]")
    selection_radio = (By.XPATH, "//td//input[@type='radio']")
    lastname_667_r = (By.XPATH, "//input[@name='lastName']")
    firstname_667_r = (By.XPATH, "//input[@name='firstName']")
    middlename_667_r = (By.XPATH, "//input[@name='middleName']")
    gender_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    individual_taxpayer_number_667_r = (By.XPATH, "//input[@name='taxCertificateNumber']")
    insurance_certificate_number_667_r = (By.XPATH, "//input[@name='insuranceCertificateNumber']")
    birthdate_667_r = (By.XPATH, "//input[@id='birthDate']")
    citizenship_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")
    birthplace_667_r = (By.XPATH, "//input[@ng-model='model.generalInformation.birthPlace']")
    maritalstatuses_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[3]")
    work_phone_667_r = (By.XPATH, "//input[@ng-model='model.workPhone']")
    mobile_phone_667_r = (By.XPATH, "//input[@ng-model='model.mobilePhone']")
    additional_phone_667_r = (By.XPATH, "//input[@ng-model='model.additionalPhone']")
    fax_667_r = (By.XPATH, "//input[@ng-model='model.fax']")
    work_email_667_r = (By.XPATH, "//input[@ng-model='model.workEmail']")
    personal_email_667_r = (By.XPATH, "//input[@ng-model='model.personalEmail']")
    web_address_667_r = (By.XPATH, "//input[@ng-model='model.webAddress']")
    permanent_registration_sub_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    permanent_registration_reg_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")
    temp_registration_sub_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[3]")
    temp_registration_reg_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[4]")
    fact_registration_sub_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[5]")
    fact_registration_reg_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[6]")
    type_document_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    series_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.series']")
    number_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.number']")
    date_issued_667_r = (By.XPATH, "//input[@id='dateIssued']")
    date_end_667_r = (By.XPATH, "//input[@id='dateEnd']")
    issue_by_667_r = (By.XPATH, "//textarea[@data-ng-model='editmodel.issuedBy']")
    issue_code_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.issuedCode']")
    education_level_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    education_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    education_form_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")
    place_institution_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.place']")
    full_name_institution_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[3]")
    start_date_education_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.startDate']")
    end_date_education_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.endDate']")
    education_directions_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[4]")
    faculty_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.faculty']")
    education_doc_number_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.educationDocNumber']")
    education_doc_date_667_r = (By.XPATH, "//input[@id='educationDocDate']")
    speciality_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[5]")
    qualification_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[6]")
    specialization_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.specialization']")
    is_main_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.isMain']")
    egc_education_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[7]")
    egc_place_667_r = (By.XPATH, "(//input[@data-ng-model='editmodel.place'])[2]")
    egc_name_institution_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.institutionText']")
    egc_start_date_667_r = (By.XPATH, "//input[@id='egc_startDate']")
    egc_end_date_667_r = (By.XPATH, "//input[@id='egc_endDate']")
    egc_academic_degree_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[8]")
    egc_academic_degree_date_667_r = (By.XPATH, "//input[@id='academicDegreeDate']")
    egc_knowledge_branches_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[9]")
    egc_diplom_number_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.diplomNumber']")
    egc_diplom_date_667_r = (By.XPATH, "//input[@id='egc_diplomDate']")
    academic_statuses_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[10]")
    diplom_number_667_r = (By.XPATH, "(//input[@data-ng-model='editmodel.diplomNumber'])[2]")
    assigment_date_667_r = (By.XPATH, "//div[@data-ng-model='editmodel.assigmentDate']/input")
    languages_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[11]")
    language_degrees_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[12]")
    dpo_education_direction_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[13]")
    dpo_education_kind_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[14]")
    dpo_kind_667_r = (By.XPATH, "(//input[@data-ng-model='editmodel.speciality'])[2]")
    dpo_name_program_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.title']")
    dpo_education_form_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[15]")
    dpo_place_667_r = (By.XPATH, "(//input[@data-ng-model='editmodel.place'])[3]")
    dpo_name_institution_667_r = (By.XPATH, "(//input[@data-ng-model='editmodel.institutionText'])[2]")
    dpo_start_date_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[16]")
    dpo_end_date_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[17]")
    dpo_hours_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.hours']")
    dpo_document_number_667_r = (By.XPATH, "//input[@data-ng-model='editmodel.documentNumber']")
    dpo_document_date_667_r = (By.XPATH, "//div[@data-ng-model='editmodel.documentDate']/input")
    dpo_funding_sources_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[18]")
    work_begin_date_667_r = (By.XPATH, "//div[@ng-model='lac.editmodel.beginDate']/input")
    work_end_date_667_r = (By.XPATH, "//div[@ng-model='lac.editmodel.endDate']/input")
    work_post_667_r = (By.XPATH, "//input[@ng-model='lac.editmodel.post']")
    work_organization_667_r = (By.XPATH, "//input[@ng-model='lac.editmodel.organization']")
    work_address_organization_667_r = (By.XPATH, "//input[@ng-model='lac.editmodel.addressOrganization']")
    work_employees_number_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    work_subject_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")
    work_region_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[3]")
    work_profile_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[4]")
    work_is_elective_667_r = (By.XPATH, "//input[@ng-model='lac.editmodel.isElective']")
    work_post_level_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[5]")
    work_activity_area_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[6]")
    work_structural_division_667_r = (By.XPATH, "//input[@id='structuralDivision']")
    work_responsibilities_667_r = (By.XPATH, "//input[@id='responsibilities']")
    has_class_rank_667_r = (By.XPATH, "//input[@ng-model='model.hasClassRank']")
    class_rank_667_r = (By.XPATH, "//input[@ng-model='model.classRank']")
    class_rank_assigned_date_667_r = (By.XPATH, "//div[@ng-model='model.classRankAssignedDate']/input")
    class_rank_assigned_by_667_r = (By.XPATH, "//input[@ng-model='model.classRankAssignedBy']")
    has_government_service_667_r = (By.XPATH, "//input[@ng-model='model.hasGovernmentService']")
    org_sub_types_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[8]")
    organization_name_667_r = (By.XPATH, "//input[@ng-model='model.organizationName']")
    computer_skills_667_r = (By.XPATH, "//textarea[@ng-model='model.computerSkills']")
    publications_667_r = (By.XPATH, "//textarea[@ng-model='model.publications']")
    recommendations_667_r = (By.XPATH, "//textarea[@ng-model='model.recommendations']")
    specialization_work_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[8]")
    specialization_is_main_667_r = (By.XPATH, "(//input[@ng-model='editmodel.isMain'])[1]")
    specialization_is_add_667_r = (By.XPATH, "(//input[@ng-model='model.organizationName'])[2]")
    award_type_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    award_name_667_r = (By.XPATH, "//textarea[@ng-model='awd.editmodel.name']")
    award_date_667_r = (By.XPATH, "//div[@ng-model='awd.editmodel.dateAwarding']/input")
    admission_form_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    approval_number_667_r = (By.XPATH, "//input[@ng-model='sst.editmodel.approvalNumber']")
    issue_date_667_r = (By.XPATH, "//div[@ng-model='sst.editmodel.issueDate']/input")
    military_rank_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    military_duty_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")
    has_military_service_667_r = (By.XPATH, "//input[@ng-model='model.hasMilitaryService']")
    military_service_from_667_r = (By.XPATH, "//div[@data-ng-model='model.militaryServiceFrom']/input")
    military_service_to_667_r = (By.XPATH, "//div[@data-ng-model='model.militaryServiceTo']/input")
    arm_kind_667_r = (By.XPATH, "//input[@ng-model='model.armKind']")
    kin_ship_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[1]")
    kin_last_name_667_r = (By.XPATH, "//input[@name='lastName']")
    kin_first_name_667_r = (By.XPATH, "//input[@name='firstName']")
    kin_middle_name_667_r = (By.XPATH, "//input[@name='middleName']")
    kin_name_changes_667_r = (By.XPATH, "//textarea[@ng-model='rin.editmodel.nameChanges']")
    kin_birth_date_667_r = (By.XPATH, "//div[@ng-model='rin.editmodel.birthDate']/input")
    kin_birth_country_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[2]")
    kin_birth_region_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[3]")
    kin_birth_area_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[4]")
    kin_birth_place_667_r = (By.XPATH, "//input[@data-ng-model='rin.editmodel.birthPlace']")
    kin_work_place_667_r = (By.XPATH, "//textarea[@ng-model='rin.editmodel.workPlace']")
    kin_living_country_667_r = (By.XPATH, "(//div[contains(@id, 's2id')])[5]")
    kin_living_address_667_r = (By.XPATH, "//input[@data-ng-model='rin.editmodel.livingAddress']")
