from pages import *
from setup import *
from locators import *


class TestSuite:

    @classmethod
    def setup_class(cls):
        """What happens BEFORE tests"""
        cls.driver = webdriver.Chrome("C:\Python34\Scripts\chromedriver.exe")
        cls.driver.maximize_window()
        cls.driver.get(Links.main_page)

    @classmethod
    def teardown_class(cls):
        """What happens AFTER tests"""
        cls.driver.quit()

    def test_doc_documents(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.scroll_to_bottom()
        p.click_by_text("Документы", 2)
        p.click_by_text("Документы", 2)
        sleep(2)
        p.click_by_text("Добавить")
        p.name_document("Эссе")
        p.upload_file("C:\\Users\\drozdoviv\\Desktop\\Проверочный.docx")
        p.click_by_text("Добавить")

    def test_doc_appform_personal_main(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        self.driver.get(Links.appform)
        Browser(self.driver).wait_for_loading()
        if "Анкета 667" in self.driver.page_source:
            p.selection_radio()
            p.click_by_text("Удалить")
            p.click_by_text("Да")
        p.click_by_text("Добавить")
        p.upload_photo("C:\\Users\\drozdoviv\\Desktop\\1.jpg")
        p.lastname_667_r("Дроздов")
        p.firstname_667_r("Илья")
        p.middlename_667_r("Владимирович")
        p.gender_667_r("Мужской")
        p.individual_taxpayer_number_667_r("6449013711")
        p.insurance_certificate_number_667_r("001-024-567 67")
        p.birthdate_667_r("01061980")
        p.citizenship_667_r("Гражданин Российской Федерации")
        p.change_citizenship_667_r("Нет")
        p.birthplace_667_r("г. Москва")
        p.wasconvicted_667_r("Нет")
        p.maritalstatuses_667_r("Состоит в зарегистрированном браке")
        p.namewaschanged_667_r("Не менял")
        p.wasabroad_667_r("Нет")
        p.click_by_text("Сохранить")

    def tes7t_doc_appform_personal_contact(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        if "Загрузить" in self.driver.page_source:
            p.click_by_text("Редактировать")
        else:
            p.click_by_text("Редактировать", 2)
        p.work_phone_667_r("9453513517")
        p.mobile_phone_667_r("5435643865")
        p.additional_phone_667_r("4675346743")
        p.fax_667_r("4675346744")
        p.work_email_667_r("kandidat@mail.net")
        p.personal_email_667_r("kandidathome@mail.net")
        p.web_address_667_r("kandidat.com")
        p.permanent_registration_sub_667_r("Алтайский край")
        p.permanent_registration_reg_667_r("Алейский район")
        p.temp_registration_sub_667_r("Алтайский край")
        p.temp_registration_reg_667_r("Алейский район")
        p.fact_registration_sub_667_r("Алтайский край")
        p.fact_registration_reg_667_r("Алейский район")
        p.click_by_text("Сохранить")

    def tes7t_doc_appform_document(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Документы, удостоверяющие")
        p.click_by_text("Добавить")
        p.type_document_667_r("Паспорт гражданина РФ")
        p.series_667_r("2654")
        p.number_667_r("132456")
        p.date_issued_667_r("15062005")
        p.issue_by_667_r("ОВД Замоскворечье")
        p.issue_code_667_r("223658")
        p.click_by_text("Сохранить")

    def tes7t_doc_appform_education_main(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        z = ControlVacancyPage(self.driver)
        z.subcontrol.stat
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Образование")
        p.click_by_text("Редактировать")
        p.education_level_667_r("Высшее образование")
        p.click_by_text("Сохранить")
        p.click_by_text("Добавить")
        p.education_667_r("Высшее образование – специалитет")
        p.education_form_667_r("Очное")
        p.place_institution_667_r("г. Москва")
        p.full_name_institution_667_r("Мытищинский институт экономики")
        p.start_date_education_667_r("2002")
        p.end_date_education_667_r("2007")
        p.education_directions_667_r("Экономика и управление")
        p.faculty_667_r("Экономика")
        p.education_doc_number_667_r("35-ГС")
        p.speciality_667_r("080100")
        p.qualification_667_r("51 - Экономист")
        p.specialization_667_r("Экономика")
        p.is_main_667_r("True")
        p.education_doc_date_667_r("04072017")
        p.click_by_text("Сохранить")

    def tes7t_doc_appform_education_egc(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Образование")
        p.click_by_text("Добавить", 2)
        p.egc_education_667_r("Аспирантура")
        p.egc_place_667_r("г. Москва")
        p.egc_name_institution_667_r("МАИ")
        p.egc_start_date_667_r("2007")
        p.egc_academic_degree_667_r("Кандидат наук")
        p.egc_academic_degree_date_667_r("20082008")
        p.egc_end_date_667_r("2008")
        p.egc_knowledge_branches_667_r("Экономические науки")
        p.egc_diplom_number_667_r("34358-П")
        p.egc_diplom_date_667_r("20092008")

    def tes7t_doc_appform_education_degree(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Образование")
        p.click_by_text("Добавить", 3)
        p.academic_statuses_667_r("Доцент")
        p.diplom_number_667_r("348-А")
        p.assigment_date_667_r("20092008")

    def tes7t_doc_appform_education_languages(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Образование")
        p.click_by_text("Добавить", 4)
        p.languages_667_r("Немецкий")
        p.language_degrees_667_r("Владеет свободно")
        p.click_by_text("Сохранить", 4)

    def tes7t_doc_appform_education_dpo(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Образование")
        p.scroll_to_bottom()
        p.click_by_text("Добавить", 5)
        p.dpo_education_direction_667_r("Организационно-экономическое")
        p.dpo_education_kind_667_r("Профессиональная переподготовка")
        p.dpo_kind_667_r("Профессиональная переподготовка")
        p.dpo_name_program_667_r("Профессиональное развитие персонала")
        p.dpo_education_form_667_r("Заочное")
        p.dpo_place_667_r("г. Москва")
        p.dpo_name_institution_667_r("МАИ")
        p.dpo_start_date_667_r("2008")
        p.dpo_end_date_667_r("2009")
        p.dpo_hours_667_r("120")
        p.dpo_document_number_667_r("89П6")
        p.dpo_funding_sources_667_r("За счет средств Федерального бюджета")
        p.dpo_document_date_667_r("20092009")

    def tes7t_doc_appform_work(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Трудовая деятельность")
        p.click_by_text("Добавить")
        p.work_begin_date_667_r("20092009")
        p.work_post_667_r("Специалист")
        p.work_organization_667_r("Федеральная Таможенная Служба")
        p.work_address_organization_667_r("г. Москва")
        p.work_employees_number_667_r("11 - 100 человек")
        p.work_subject_667_r("Алтайский край")
        p.work_region_667_r("Алейский район")
        p.work_profile_667_r("Текстильное производство")
        p.work_is_elective_667_r("True")
        p.work_post_level_667_r("Специалист")
        p.work_activity_area_667_r("Другое")
        p.work_structural_division_667_r("Бухгалтерский учет")
        p.work_responsibilities_667_r("Рассчет заработной платы сотрудников организации")
        p.click_by_text("Сохранить")

    def tes7t_doc_appform_class_rank(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Трудовая деятельность")
        p.click_by_text("Редактировать", 3)
        sleep(1)
        p.has_class_rank_667_r("True")
        p.class_rank_667_r("Секретарь государственной гражданской службы Российской Федерации 1 класса")
        sleep(2)
        p.class_rank_assigned_by_667_r("Федеральная Таможенная Служба")
        p.has_government_service_667_r("True")
        p.org_sub_types_667_r("Городской округ")
        p.organization_name_667_r("Федеральная Таможенная Служба")
        p.computer_skills_667_r("Продвинутый пользователь")
        p.publications_667_r("Отсутствуют")
        p.recommendations_667_r("Отсутствуют")
        p.class_rank_assigned_date_667_r("20092009")
        sleep(1)
        self.driver.refresh()
        p.scroll_to_bottom()

    def tes7t_doc_appform_specialization(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Трудовая деятельность")
        p.click_by_text("Добавить", 3)
        p.scroll_to_bottom()
        sleep(1)
        p.specialization_work_667_r("Экономика и финансы")
        p.specialization_is_main_667_r("True")
        p.click_by_text("Сохранить", 3)

    def tes7t_doc_appform_award(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Поощрения")
        p.click_by_text("Добавить")
        p.award_type_667_r("благодарность")
        p.award_name_667_r("За заслуги")
        p.award_date_667_r("16042016")
        p.click_by_text("Сохранить")

    def tes7t_doc_appform_state_secret(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Допуск к государственной тайне")
        p.click_by_text("Добавить")
        p.admission_form_667_r("Вторая форма")
        p.approval_number_667_r("85")
        p.issue_date_667_r("11022015")

    def tes7t_doc_appform_military(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Воинский учет")
        p.click_by_text("Редактировать")
        p.military_rank_667_r("ефрейтор")
        p.military_duty_667_r("Военнообязанный")
        p.has_military_service_667_r("True")
        p.arm_kind_667_r("Сухопутные")
        p.military_service_from_667_r("20022000")
        p.military_service_to_667_r("20022001")
        self.driver.refresh()

    def tes7t_doc_appform_kin(self):
        HeaderPage(self.driver).login("drozdoviv@quarta.su", "123123/")
        p = DocumentsPage(self.driver)
        p.has_appform()
        p.click_by_text("Сведения о близких родственниках")
        p.click_by_text("Добавить")
        p.kin_ship_667_r("Сын")
        p.kin_last_name_667_r("Иванов")
        p.kin_first_name_667_r("Илья")
        p.kin_middle_name_667_r("Глебович")
        p.kin_name_changes_667_r("Не менял")
        p.kin_birth_country_667_r("Россия")
        p.kin_birth_region_667_r("г. Москва")
        sleep(1)
        p.kin_birth_area_667_r("Центральный")
        p.kin_birth_place_667_r("г. Москва")
        p.kin_work_place_667_r("Отсутствует")
        p.kin_living_country_667_r("Россия")
        p.kin_living_address_667_r("Москва")
        p.kin_birth_date_667_r("15062009")
